# Generated by Django 2.2.6 on 2019-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteslist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
