# Generated by Django 2.2.6 on 2019-10-23 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notey', '0002_noteslist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteslist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noteslist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
