# Generated by Django 2.2.6 on 2019-10-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notey', '0004_noteslistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesListItem',
        ),
    ]
