# Generated by Django 2.2.6 on 2019-10-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notey', '0006_noteslistitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesListItem',
        ),
    ]
